/// The kings of Judah and Israel on Thiele's chronology.
///
/// Backing data: `assets/world_chart/hebrew_kings.json`, built by
/// `scripts/build_hebrew_kings.py`, which carries the citation for
/// every figure. Years are negative for BC, matching
/// `assets/world_chart/bible_timeline.json` and `assets/world_chart/family_tree.json`.
library;

enum Kingdom { united, judah, israel }

/// A reign is not one interval. Thiele's whole reconstruction turns on
/// reigns that run *alongside* each other, so a king carries a list of
/// spans rather than a single start and end:
///
///   [sole]       reigning alone
///   [coregency]  reigning with his father — six in Judah, one in
///                Israel, on Thiele's reckoning
///   [rival]      a contested parallel claim: Tibni against Omri, and
///                Pekah in Gilead against Menahem and Pekahiah
enum SpanKind {
  sole(heldThrone: true),
  coregency(heldThrone: true),
  rival(heldThrone: false);

  const SpanKind({required this.heldThrone});

  /// Whether a span of this kind puts the man on the throne, for
  /// [HebrewKing.isRival] and so for every reigning count in the app.
  ///
  /// THIS FIELD EXISTS TO MAKE A NEW KIND A COMPILE ERROR. `isRival`
  /// used to read `spans.every((s) => s.kind == SpanKind.rival)` — a
  /// blacklist of one name out of an open set. The four `switch`
  /// expressions in `hebrew_kings_page.dart` are exhaustive, so a new
  /// kind stops the RENDERER compiling; the COUNTER kept compiling and
  /// would have tallied a `captivity` or `exile` span as a reign. A
  /// required constructor argument puts the counter on the renderer's
  /// footing: the fourth value cannot be written without answering.
  ///
  /// `heldThrone: false` means the span is tallied under
  /// `kingsTallyRival`, "Rival claimants · {n}". If a future kind is
  /// neither a reign nor a rival claim — captivity, exile, an
  /// interregnum — do NOT write `false` here. The tally needs a third
  /// bucket and a third string, and this is the line that makes you
  /// decide instead of quietly joining Tibni.
  final bool heldThrone;
}

class ReignSpan {
  const ReignSpan({required this.kind, required this.start, required this.end});

  final SpanKind kind;
  final int start;
  final int end;

  int get years => end - start;

  static ReignSpan fromJson(Map<String, dynamic> j) => ReignSpan(
        // THROWS RATHER THAN GUESSING. This used to be
        // `_ => SpanKind.sole`, which read an unrecognised token as the
        // single most consequential thing a span can be — a full sole
        // reign — and so inflated every count that touches it. The
        // asset is generated by `scripts/build_hebrew_kings.py` and
        // ships inside the bundle, and `test/hebrew_kings_test.dart`
        // parses the real file, so an unknown kind is a red test on the
        // author's machine, never a dead chart on a reader's device.
        // The two number fields below have always thrown on bad input;
        // `kind` was the one field where malformed data was promoted.
        kind: switch (j['kind'] as String?) {
          'sole' => SpanKind.sole,
          'coregency' => SpanKind.coregency,
          'rival' => SpanKind.rival,
          final other => throw FormatException(
              'hebrew_kings.json: unknown span kind ${other ?? 'null'}'),
        },
        start: (j['start'] as num).toInt(),
        end: (j['end'] as num).toInt(),
      );
}

class HebrewKing {
  const HebrewKing({
    required this.id,
    required this.kingdom,
    required this.house,
    required this.names,
    required this.spans,
    required this.reignStart,
    required this.reignEnd,
    this.altNames,
    this.notes,
    this.kingsRef,
    this.chroniclesRef,
    this.accessionRef,
  });

  final String id;
  final Kingdom kingdom;

  /// Dynasty, given as the id of the king who founded it (`david`,
  /// `omri`, `jehu`…). Storing an id rather than a display string means
  /// "House of Omri" localises through the king's own name and adds no
  /// second translation surface to drift.
  final String house;

  final Map<String, String> names;
  final Map<String, String>? altNames;
  final Map<String, String>? notes;

  final List<ReignSpan> spans;
  final int reignStart;
  final int reignEnd;

  /// The passage in Kings, and — for Judah only — the parallel account
  /// in Chronicles. Chronicles tells the story of the southern kingdom,
  /// so [chroniclesRef] is null for every northern king. That absence
  /// is information, and the detail panel says so rather than hiding
  /// the row.
  final String? kingsRef;
  final String? chroniclesRef;

  /// The verse that dates this king's accession by the regnal year of
  /// his contemporary in the other kingdom — "in the twentieth year of
  /// Jeroboam king of Israel, Asa began to reign over Judah". These
  /// synchronisms are the raw material of Thiele's system, not
  /// decoration.
  final String? accessionRef;

  /// True when this man never held the throne on his own account —
  /// every one of his spans is a [SpanKind.rival] claim.
  ///
  /// THIS IS THE ONLY TEST FOR RIVAL STATUS IN THE APP, and it reads
  /// `spans`, never a list of names. Tibni is the one man in the file
  /// it is true of: 1 Kings 16:21-22 gives him no regnal formula and
  /// never says he reigned, so he is not among the canonical nineteen
  /// kings of Israel, and his dates are Thiele's inference. Omri is
  /// NOT rival by this test — his `rival` span is followed by a `sole`
  /// one, because the four years against Tibni ended with him on the
  /// throne alone.
  ///
  /// The `isNotEmpty` guard is not decoration: `every` on an empty list
  /// is true, so a king whose `spans` failed to parse would silently
  /// be demoted to a claimant and drop out of every reigning count.
  ///
  /// Reads [SpanKind.heldThrone] rather than testing against
  /// `SpanKind.rival` by name, so that a kind added to the enum has to
  /// declare which side of this line it falls on instead of defaulting
  /// into the reigning count. Identical on the shipped asset, where the
  /// three kinds make "every span is rival" and "no span held the
  /// throne" the same sentence.
  bool get isRival =>
      spans.isNotEmpty && !spans.any((s) => s.kind.heldThrone);

  /// Whether this man's arc is more than one interval — he has several
  /// spans, or his single span is not a plain sole reign — and so needs
  /// the parts named beneath it.
  ///
  /// EMPTY-SPANS SAFE, WHICH IS THE WHOLE POINT. `wheel_sheets.dart`
  /// asked this inline as `spans.length > 1 || spans.first.kind !=
  /// SpanKind.sole`; `||` short-circuits the wrong way round, so a king
  /// whose spans failed to parse reached `spans.first` on an empty list
  /// and threw the `StateError` that [isRival]'s guard exists to
  /// prevent one line above. Ten kings answer true on the shipped
  /// asset: the nine with more than one span — the six Judean
  /// co-regents, Jeroboam II, and Omri and Pekah, whose rival span
  /// precedes a sole one — plus Tibni, whose single span is a rival
  /// claim rather than a reign.
  bool get hasCompoundReign =>
      spans.length > 1 ||
      (spans.isNotEmpty && spans.first.kind != SpanKind.sole);

  ReignSpan? get soleReign {
    for (final s in spans) {
      if (s.kind == SpanKind.sole) return s;
    }
    return null;
  }

  ReignSpan? get overlapSpan {
    for (final s in spans) {
      if (s.kind != SpanKind.sole) return s;
    }
    return null;
  }

  int get totalYears => reignEnd - reignStart;

  String nameFor(String locale) =>
      names[locale] ?? names['en'] ?? id;

  String? altNameFor(String locale) =>
      altNames?[locale] ?? altNames?['en'];

  String? noteFor(String locale) => notes?[locale] ?? notes?['en'];

  static Map<String, String>? _strings(dynamic v) {
    if (v is! Map) return null;
    return {
      for (final e in v.entries)
        if (e.value is String) e.key.toString(): e.value as String,
    };
  }

  static HebrewKing fromJson(Map<String, dynamic> j) => HebrewKing(
        id: j['id'] as String,
        // Same defect as the span kind above, and worse in effect:
        // `contemporariesOf` returns an empty list for the united
        // monarchy, so a typo'd kingdom used to drop a king silently
        // out of every synchronism instead of failing. All 42 records
        // write `united` out in full, so nothing relies on the default.
        kingdom: switch (j['kingdom'] as String?) {
          'judah' => Kingdom.judah,
          'israel' => Kingdom.israel,
          'united' => Kingdom.united,
          final other => throw FormatException(
              'hebrew_kings.json: unknown kingdom ${other ?? 'null'}'),
        },
        house: (j['house'] as String?) ?? '',
        names: _strings(j['name']) ?? const {},
        altNames: _strings(j['altName']),
        notes: _strings(j['note']),
        spans: ((j['spans'] as List?) ?? const [])
            .whereType<Map<String, dynamic>>()
            .map(ReignSpan.fromJson)
            .toList(),
        reignStart: (j['reignStart'] as num).toInt(),
        reignEnd: (j['reignEnd'] as num).toInt(),
        kingsRef: j['kingsRef'] as String?,
        chroniclesRef: j['chroniclesRef'] as String?,
        accessionRef: j['accessionRef'] as String?,
      );
}

class KingsEpoch {
  const KingsEpoch({
    required this.id,
    required this.year,
    required this.names,
    this.ref,
  });

  final String id;
  final int year;
  final Map<String, String> names;
  final String? ref;

  String nameFor(String locale) => names[locale] ?? names['en'] ?? id;

  static KingsEpoch fromJson(Map<String, dynamic> j) => KingsEpoch(
        id: j['id'] as String,
        year: (j['year'] as num).toInt(),
        names: HebrewKing._strings(j['name']) ?? const {},
        ref: j['ref'] as String?,
      );
}

/// THE OVERLAP RULE, written once.
///
/// The comparison is over CLOSED intervals, and that is deliberate.
/// Ahaziah of Judah reigned only in 841 BC and Jehu of Israel came to
/// the throne in 841 BC — Jehu killed him — so a half-open test would
/// report the two men who met that year as never having overlapped.
/// Several reigns here are a single year or less (Zimri's seven days,
/// Shallum's month), and a half-open rule erases them.
///
/// Nor is a touch at one end an artefact to be filtered out. Asa of
/// Judah acceded in Jeroboam I's twentieth year (1 Kings 15:9) and
/// Nadab in Asa's second (1 Kings 15:25); on Thiele's figures the two
/// men share about a year and on Albright's about twelve. The shared
/// year is the synchronism the text itself supplies, so it counts.
///
/// [reignsOverlap] and [reignTouchesYear] both go through here so that
/// the chart, the wheel sheet and the year lookup cannot come to
/// disagree about who was reigning when.
bool closedIntervalsOverlap(int aStart, int aEnd, int bStart, int bEnd) =>
    aStart <= bEnd && bStart <= aEnd;

/// Two kings are contemporaries when their reigns share any year.
///
/// COMPARED OVER THE HULL, NOT THE SPANS, and that is a choice rather
/// than an oversight. `reignStart`/`reignEnd` are what the chart bars
/// and the wheel arcs are DRAWN from — `wheel_sheets.dart` calls the
/// arc the hull and the spans the reign, because two arcs for one man
/// cannot be read as one man — so counting over the spans would let the
/// count say "never met" about a year the picture shows them both
/// reigning. The hull is also the only field a king with unparsed spans
/// still has, and losing him from every list is the silent
/// disappearance [HebrewKing.isRival]'s guard exists to prevent.
///
/// It costs nothing today: `scripts/build_hebrew_kings.py` DERIVES the
/// two fields from the spans, and `test/hebrew_kings_test.dart` pins
/// the result over the shipped asset — spans contiguous, `reignStart ==
/// spans.first.start`, `reignEnd == spans.last.end`. Measured on all 42
/// kings: no gaps, so hull and span-union agree on every one of the 861
/// pairs. A deposed-and-restored king would break that contiguity test
/// first, which is the right place to fail: a gap is a modelling
/// decision about what the arc means, not something this line should
/// quietly absorb.
bool reignsOverlap(HebrewKing a, HebrewKing b) => closedIntervalsOverlap(
      a.reignStart,
      a.reignEnd,
      b.reignStart,
      b.reignEnd,
    );

/// Whether [k] was on the throne in [year] — the same closed-interval
/// rule applied to a window one year wide. Years are negative for BC.
bool reignTouchesYear(HebrewKing k, int year) =>
    closedIntervalsOverlap(k.reignStart, k.reignEnd, year, year);
