from pathlib import Path
import json,hashlib
w=Path(__file__).resolve().parents[1];s=w
def loc(en,hs,ht):return {'en':en,'zh-Hans':hs,'zh-Hant':ht}
def event(id,title,place,period,summary,refs,hour=None):
 return dict(id=id,title=loc(*title),place=loc(*place),period=loc(*period),summary=loc(*summary),refs=refs,clockHour=hour)
E=[]
def add(*a,**kw):E.append(event(*a,**kw))
add('supper',('The Last Supper','最后的晚餐','最後的晚餐'),('Jerusalem · prepared room','耶路撒冷 · 预备的房间','耶路撒冷 · 預備的房間'),('Evening · hour unspecified','晚上 · 未记确切时辰','晚上 · 未記確切時辰'),('Jesus shares the meal with his disciples and gives the bread and cup. The Gospels do not give a modern clock time.','耶稣与门徒同席，分饼和杯。福音书没有给出现代钟表时间。','耶穌與門徒同席，分餅和杯。福音書沒有給出現代鐘錶時間。'),['Matthew 26:20-30','Mark 14:17-26','Luke 22:14-20'])
add('garden',('Prayer in Gethsemane','客西马尼祷告','客西馬尼禱告'),('Gethsemane · Mount of Olives','客西马尼 · 橄榄山','客西馬尼 · 橄欖山'),('Night · hour unspecified','夜间 · 未记确切时辰','夜間 · 未記確切時辰'),('Jesus prays that the Father’s will be done and asks the disciples to watch and pray.','耶稣祷告愿父的旨意成就，并嘱咐门徒警醒祷告。','耶穌禱告願父的旨意成就，並囑咐門徒警醒禱告。'),['Matthew 26:36-46','Mark 14:32-42','Luke 22:39-46'])
add('arrest',('Betrayal and arrest','被出卖与被捕','被出賣與被捕'),('Gethsemane / garden across the Kidron','客西马尼／汲沦溪对面的园子','客西馬尼／汲淪溪對面的園子'),('Night · hour unspecified','夜间 · 未记确切时辰','夜間 · 未記確切時辰'),('Judas arrives with an armed party. Jesus is arrested; the disciples flee. John describes the garden across the Kidron.','犹大带人来到，耶稣被捕，门徒离散。约翰记载地点在汲沦溪对面的园子。','猶大帶人來到，耶穌被捕，門徒離散。約翰記載地點在汲淪溪對面的園子。'),['Matthew 26:47-56','Mark 14:43-52','Luke 22:47-53','John 18:1-12'])
add('annas',('Brought to Annas','先被带到亚那面前','先被帶到亞那面前'),('Annas · exact building unspecified','亚那面前 · 未记具体建筑','亞那面前 · 未記具體建築'),('After arrest · hour unspecified','被捕后 · 未记确切时辰','被捕後 · 未記確切時辰'),('John records that Jesus is taken first to Annas, questioned, and then sent bound to Caiaphas.','约翰记载耶稣先被带到亚那面前受问，随后被捆着送往该亚法。','約翰記載耶穌先被帶到亞那面前受問，隨後被捆著送往該亞法。'),['John 18:13-24'])
add('caiaphas',('Questioned before the high priest','在大祭司面前受审','在大祭司面前受審'),('High priest’s residence','大祭司的院宅','大祭司的院宅'),('Night · hour unspecified','夜间 · 未记确切时辰','夜間 · 未記確切時辰'),('Witnesses accuse Jesus. He is questioned about being the Messiah, condemned and mistreated.','见证人控告耶稣；他被问是否为基督，随后被定罪并受侮辱。','見證人控告耶穌；他被問是否為基督，隨後被定罪並受侮辱。'),['Matthew 26:57-68','Mark 14:53-65'])
add('peter',('Peter denies Jesus','彼得三次不认主','彼得三次不認主'),('High priest’s courtyard','大祭司的院子','大祭司的院子'),('Before the cockcrow · hour unspecified','鸡叫以前 · 未记确切时辰','雞叫以前 · 未記確切時辰'),('Peter denies knowing Jesus three times. The cockcrow is a narrative marker, not a stated 3 a.m. appointment.','彼得三次否认认识耶稣。鸡叫是叙事标记，经文并未说是凌晨三点。','彼得三次否認認識耶穌。雞叫是敘事標記，經文並未說是凌晨三點。'),['Matthew 26:69-75','Mark 14:66-72','Luke 22:54-62','John 18:15-18','John 18:25-27'])
add('council',('The council meets at daybreak','天亮时公会审问','天亮時公會審問'),('Council · Jerusalem','公会 · 耶路撒冷','公會 · 耶路撒冷'),('Daybreak / early morning','天亮／清早','天亮／清早'),('Luke places the council’s questioning at daybreak. Matthew and Mark describe an early-morning consultation before delivery to Pilate.','路加把公会的审问记在天亮时；马太和马可记载清早商议后把耶稣交给彼拉多。','路加把公會的審問記在天亮時；馬太和馬可記載清早商議後把耶穌交給彼拉多。'),['Luke 22:66-71','Matthew 27:1-2','Mark 15:1'])
add('pilate',('Before Pontius Pilate','在彼拉多面前','在彼拉多面前'),('Praetorium / governor’s judgment place','总督府／审判处','總督府／審判處'),('Early morning · hour unspecified','清早 · 未记确切时辰','清早 · 未記確切時辰'),('Jesus is delivered to the governor and questioned. John explicitly calls the arrival early.','耶稣被交给总督受审；约翰明确说到达时是清早。','耶穌被交給總督受審；約翰明確說到達時是清早。'),['Matthew 27:11-14','Mark 15:1-5','Luke 23:1-5','John 18:28-38'])
add('herod',('Sent to Herod','被送往希律那里','被送往希律那裡'),('Herod in Jerusalem · exact building unspecified','耶路撒冷的希律那里 · 未记具体建筑','耶路撒冷的希律那裡 · 未記具體建築'),('During the hearings · hour unspecified','受审期间 · 未记确切时辰','受審期間 · 未記確切時辰'),('Luke records a hearing before Herod, mockery, and Jesus being sent back to Pilate.','路加记载希律审问并戏弄耶稣，然后把他送回彼拉多那里。','路加記載希律審問並戲弄耶穌，然後把他送回彼拉多那裡。'),['Luke 23:6-12'])
add('sentence',('Barabbas released; Jesus condemned','释放巴拉巴，判耶稣受刑','釋放巴拉巴，判耶穌受刑'),('Pilate’s judgment seat · Gabbatha (John)','彼拉多审判席 · 厄巴大（约翰）','彼拉多審判席 · 厄巴大（約翰）'),('John: about the sixth hour · chronology differs','约翰：约第六时 · 与马可时序不同','約翰：約第六時 · 與馬可時序不同'),('John 19:14 places Jesus before Pilate at about the sixth hour; Mark 15:25 places crucifixion at the third hour. These statements are retained separately. This wheel does not choose a disputed clock-system explanation.','约19:14记耶稣在彼拉多面前时约第六时；可15:25记钉十字架为第三时。本图分别保留这两项记载，不擅自选定有争议的计时解释。','約19:14記耶穌在彼拉多面前時約第六時；可15:25記釘十字架為第三時。本圖分別保留這兩項記載，不擅自選定有爭議的計時解釋。'),['Matthew 27:15-26','Mark 15:6-15','Luke 23:13-25','John 19:13-16'])
add('mockery',('Scourged and mocked','受鞭打与戏弄','受鞭打與戲弄'),('Governor’s headquarters · soldiers’ gathering','总督府 · 兵丁聚集处','總督府 · 兵丁聚集處'),('Before crucifixion · hour unspecified','钉十字架以前 · 未记确切时辰','釘十字架以前 · 未記確切時辰'),('Soldiers mock Jesus with a robe and crown of thorns. John narrates the scourging before the final judgment scene; Matthew and Mark place the soldiers’ mockery after the sentence.','兵丁给耶稣穿袍、戴荆棘冠冕并戏弄他。约翰把鞭打记在最终审判场景之前；马太与马可把兵丁戏弄记在宣判之后。','兵丁給耶穌穿袍、戴荊棘冠冕並戲弄他。約翰把鞭打記在最終審判場景之前；馬太與馬可把兵丁戲弄記在宣判之後。'),['Matthew 27:26-31','Mark 15:15-20','John 19:1-5'])
add('road',('On the way to Golgotha','前往各各他','前往各各他'),('Road to Golgotha · precise route unspecified','通往各各他的路 · 未记具体路线','通往各各他的路 · 未記具體路線'),('Before crucifixion · hour unspecified','钉十字架以前 · 未记确切时辰','釘十字架以前 · 未記確切時辰'),('John says Jesus goes out bearing the cross. The Synoptic Gospels name Simon of Cyrene carrying it; Luke also records Jesus speaking to the women.','约翰记耶稣背着十字架出去；符类福音记古利奈人西门背十字架，路加还记耶稣向妇女说话。','約翰記耶穌背著十字架出去；符類福音記古利奈人西門背十字架，路加還記耶穌向婦女說話。'),['Matthew 27:32-34','Mark 15:21-23','Luke 23:26-31','John 19:17'])
add('cross',('Jesus is crucified','耶稣被钉十字架','耶穌被釘十字架'),('Golgotha · the place of a skull','各各他 · 髑髅地','各各他 · 髑髏地'),('Mark: third hour ≈ 9 a.m.','马可：第三时 ≈ 上午9时','馬可：第三時 ≈ 上午9時'),('Mark gives the third hour. The modern 9 a.m. label is an approximate conversion from daytime hours counted from sunrise, not an exact minute recorded by Scripture.','马可记第三时。上午9时是按日出起算白昼时辰的大致换算，并非经文记载的精确分钟。','馬可記第三時。上午9時是按日出起算白晝時辰的大致換算，並非經文記載的精確分鐘。'),['Mark 15:24-28','Matthew 27:35-38','Luke 23:32-34','John 19:18-24'],9)
add('taunts',('Mockery at the cross','十字架旁的讥诮','十字架旁的譏誚'),('Golgotha','各各他','各各他'),('While on the cross · hour unspecified','在十字架上 · 未记确切时辰','在十字架上 · 未記確切時辰'),('Passers-by and leaders mock Jesus. Luke records the conversation with the repentant criminal.','路人和领袖讥诮耶稣；路加记载他与悔改的犯人对话。','路人和領袖譏誚耶穌；路加記載他與悔改的犯人對話。'),['Matthew 27:39-44','Mark 15:29-32','Luke 23:35-43'])
add('mother',('Mother and beloved disciple','母亲与所爱的门徒','母親與所愛的門徒'),('Beside Jesus’ cross','耶稣十字架旁','耶穌十字架旁'),('While on the cross · hour unspecified','在十字架上 · 未记确切时辰','在十字架上 · 未記確切時辰'),('Jesus entrusts his mother and the beloved disciple to one another. John gives no clock hour for this scene.','耶稣把母亲和所爱的门徒彼此托付；约翰没有记此事的钟点。','耶穌把母親和所愛的門徒彼此託付；約翰沒有記此事的鐘點。'),['John 19:25-27'])
add('darkness',('Darkness over the land','遍地黑暗','遍地黑暗'),('The land · Jesus remains at Golgotha','遍地 · 耶稣仍在各各他','遍地 · 耶穌仍在各各他'),('Sixth to ninth hour ≈ noon–3 p.m.','第六至第九时 ≈ 正午至下午3时','第六至第九時 ≈ 正午至下午3時'),('Matthew, Mark and Luke describe darkness from about the sixth hour until the ninth. The shaded outer arc marks this stated interval.','马太、马可和路加记约第六时至第九时遍地黑暗。外圈阴影表示这一经文所记的时段。','馬太、馬可和路加記約第六時至第九時遍地黑暗。外圈陰影表示這一經文所記的時段。'),['Matthew 27:45','Mark 15:33','Luke 23:44-45'],12)
add('death',('The final cry and Jesus’ death','最后的呼喊与耶稣的死','最後的呼喊與耶穌的死'),('Golgotha','各各他','各各他'),('About the ninth hour ≈ 3 p.m.; death follows','约第九时 ≈ 下午3时；随后断气','約第九時 ≈ 下午3時；隨後斷氣'),('Matthew and Mark place the cry about the ninth hour, followed by Jesus’ death. Luke and John record additional final words without giving a separate exact hour. The accounts are read side by side, not forced into an undocumented order of sayings.','马太和马可记约第九时耶稣呼喊，随后断气。路加和约翰记另一些最后的话，却未另记精确时辰。本图并列阅读，不强行编排未有记载的话语顺序。','馬太和馬可記約第九時耶穌呼喊，隨後斷氣。路加和約翰記另一些最後的話，卻未另記精確時辰。本圖並列閱讀，不強行編排未有記載的話語順序。'),['Matthew 27:46-50','Mark 15:34-37','Luke 23:46','John 19:28-30'],15)
add('witness',('The curtain and the witnesses','幔子与见证人','幔子與見證人'),('Temple; Golgotha and nearby observers','圣殿；各各他与旁观的人','聖殿；各各他與旁觀的人'),('Around Jesus’ death · exact sequence varies','耶稣死亡前后 · 各记载顺序有别','耶穌死亡前後 · 各記載順序有別'),('The Synoptic Gospels record the torn temple curtain and the centurion’s response. Matthew also records an earthquake; Luke narrates the curtain before the final cry.','符类福音记圣殿幔子裂开及百夫长的回应。马太还记地震；路加把幔子裂开记在最后呼喊之前。','符類福音記聖殿幔子裂開及百夫長的回應。馬太還記地震；路加把幔子裂開記在最後呼喊之前。'),['Matthew 27:51-56','Mark 15:38-41','Luke 23:45-49'])
add('pierced',('Jesus’ side is pierced','耶稣肋旁被刺','耶穌肋旁被刺'),('Golgotha','各各他','各各他'),('After death · before removal','死后 · 被取下以前','死後 · 被取下以前'),('John records that the soldiers do not break Jesus’ legs because he is already dead; one pierces his side.','约翰记兵丁见耶稣已死，没有打断他的腿，却有兵丁刺他的肋旁。','約翰記兵丁見耶穌已死，沒有打斷他的腿，卻有兵丁刺他的肋旁。'),['John 19:31-37'])
add('burial',('Burial before the Sabbath','安息日前安葬','安息日前安葬'),('New tomb · garden near the crucifixion (John)','新坟墓 · 钉十字架处附近的园子（约翰）','新墳墓 · 釘十字架處附近的園子（約翰）'),('Evening / preparation day · no exact hour','傍晚／预备日 · 未记确切时辰','傍晚／預備日 · 未記確切時辰'),('Joseph requests the body; Jesus is laid in a tomb. John names Nicodemus and the nearby garden. No exact modern burial time is stated.','约瑟求取遗体，耶稣被安放在坟墓里。约翰记尼哥底母和附近的园子；未记现代钟表的精确安葬时间。','約瑟求取遺體，耶穌被安放在墳墓裡。約翰記尼哥底母和附近的園子；未記現代鐘錶的精確安葬時間。'),['Matthew 27:57-61','Mark 15:42-47','Luke 23:50-56','John 19:38-42'])
meta={'schema':1,'editorial':True,'checkedAt':'2026-10-01','sourcePassages':['Matthew 26-27','Mark 14-15','Luke 22-23','John 18-19'],'sources':[f'https://www.biblegateway.com/passage/?search={v}&version=KJV' for v in ['Matthew%2026-27','Mark%2014-15','Luke%2022-23','John%2018-19']],'method':'Short editorial summaries, parallel Gospel references. Only explicit third/sixth/ninth daytime hours have approximate modern clock markers. Untimed scenes have no invented clock coordinate. Event order is a reading guide; John’s hearing time and differing narrative placement are explicitly retained.'}
for repo in [w]:(repo/'assets/passion_wheel.json').write_text(json.dumps({'_meta':meta,'events':E},ensure_ascii=False,indent=2)+'\n')
# Each principle has a literal sermon anchor and an editorial summary, not a newly
# attributed quote. The UI loads the complete existing reference index per source.
P=[
('turn-other-cheek', '010', 'A person who turns the other cheek is one who trusts in God for his defense.', ('Turning the other cheek', '转脸原则 · 不以报复回应', '轉臉原則 · 不以報復回應'), ('The sermon explains turning the other cheek as trusting God for our defence and judgment, rather than taking revenge. It connects Jesus’ teaching with waiting on the Lord in Psalm 37.', '讲道把转过另一边脸理解为信靠神的保护与判断，而非自行报复；并把耶稣的教导与诗篇37篇等候神相连。', '講道把轉過另一邊臉理解為信靠神的保護與判斷，而非自行報復；並把耶穌的教導與詩篇37篇等候神相連。')),
('follow-face-back','194-1','It is in following the person that you know better and better',('Knowing God by following him · face and back','跟随神而认识神 · 面与背','跟隨神而認識神 · 面與背'),('The face-and-back illustration distinguishes observing from following. Moses seeks God’s presence to lead the people; knowing God grows through following, not merely seeing a display.','面与背的比喻区分旁观和跟随。摩西求神同在带领百姓；认识神是在跟随中加深，并不只是看见奇事。','面與背的比喻區分旁觀和跟隨。摩西求神同在帶領百姓；認識神是在跟隨中加深，並不只是看見奇事。')),
('golden-rule','043','the negative form is a weak form',('Taking the initiative in love','主动以爱待人','主動以愛待人'),('The Golden Rule calls for active good toward others, beyond merely avoiding harm. Treat people as you would wish to be treated.','金律要求主动善待人，不只是避免伤害；愿别人怎样待自己，也照样待人。','金律要求主動善待人，不只是避免傷害；願別人怎樣待自己，也照樣待人。')),
('love-god-neighbour','047','your relationship with God is the same as your relationship with people',('Love of God and love of people','爱神与爱人的关系','愛神與愛人的關係'),('A claimed love for God is tested in real relationships. Loving the visible brother cannot be separated from loving the unseen God.','宣称爱神，要在真实的人际关系中受检验；爱看得见的弟兄与爱看不见的神不能分开。','宣稱愛神，要在真實的人際關係中受檢驗；愛看得見的弟兄與愛看不見的神不能分開。')),
('kingdom-first','049','when you love the Lord more than father or mother',('Putting the Lord first','以主为先','以主為先'),('Putting the Lord first does not mean loving family less. His love purifies and strengthens how we love them; discipleship also requires counting its cost.','以主为先并不表示少爱家人；他的爱洁净并坚固对家人的爱。作门徒也要计算代价。','以主為先並不表示少愛家人；他的愛潔淨並堅固對家人的愛。作門徒也要計算代價。')),
('faith-fear','053','faith is the exact opposite of fear',('Faith in the face of fear','在惧怕中信靠','在懼怕中信靠'),('Jesus’ repeated “fear not” directs disciples toward trust in the Father. Faith addresses the fears that hinder following him.','耶稣反复说不要怕，引导门徒信靠父；信心面对拦阻跟随主的惧怕。','耶穌反覆說不要怕，引導門徒信靠父；信心面對攔阻跟隨主的懼怕。')),
('receiving','056','The receiving must be for the right reason',('Receiving God’s messenger','接待神所差来的人','接待神所差來的人'),('Receive a messenger for the word of God he carries, rather than personality or charm. The sermon connects receiving Christ’s representatives with receiving Christ.','接待使者，是因他所带来的神的话，而非个人魅力；讲道把接待基督的代表与接待基督相连。','接待使者，是因他所帶來的神的話，而非個人魅力；講道把接待基督的代表與接待基督相連。')),
('humility','057','God resists the proud and gives grace to the humble',('Grace for the humble','神赐恩给谦卑的人','神賜恩給謙卑的人'),('True greatness is expressed through humility. The sermon connects John the Baptist’s attitude with Jesus’ lowliness and God’s grace to the humble.','真正的伟大表现在谦卑中；讲道把施洗约翰的态度、耶稣的柔和谦卑与神赐恩给谦卑者相连。','真正的偉大表現在謙卑中；講道把施洗約翰的態度、耶穌的柔和謙卑與神賜恩給謙卑者相連。')),
('rest-service','063','when you serve God, you have truly',('Rest and service','安息与事奉','安息與事奉'),('The sermon reads Sabbath rest through belonging to and serving God. It uses David and the priests to explain why rest is more than inactivity.','讲道从归属神、事奉神来理解安息，并以大卫和祭司说明安息不只是停止活动。','講道從歸屬神、事奉神來理解安息，並以大衛和祭司說明安息不只是停止活動。')),
('hear-response','075','Take heed. Watch. Be careful how you hear',('Taking care how we hear','谨慎怎样听','謹慎怎樣聽'),('Hearing brings responsibility: God’s word calls for a response. The sermon warns against receiving light while refusing to live by it.','听道带来责任，神的话要求回应；讲道警告人不可领受光却拒绝按光生活。','聽道帶來責任，神的話要求回應；講道警告人不可領受光卻拒絕按光生活。')),
('humble-exalted','099','He who humbles himself, God will exalt',('Humbling ourselves before God','在神面前降卑','在神面前降卑'),('In the Pharisee and tax collector, self-exaltation is contrasted with pleading for mercy. God, rather than our comparison with others, gives the verdict.','法利赛人与税吏的比喻对照自高和求怜悯；判定在神，不在我们与别人的比较。','法利賽人與稅吏的比喻對照自高和求憐憫；判定在神，不在我們與別人的比較。')),
('agreement','116','openness, union, and agreement between at least two or three people',('Openness and agreement','敞开与同心','敞開與同心'),('The sermon links truthful communication, reconciliation, witness and shared prayer. Agreement grows through dealing honestly with offence, not hiding it.','讲道联系真实沟通、和好、见证与共同祷告；同心需要诚实处理得罪人的事，而不是掩盖。','講道聯繫真實溝通、和好、見證與共同禱告；同心需要誠實處理得罪人的事，而不是掩蓋。')),
('grace-good-works','118','The first principle is grace',('Grace leading to good works','恩典引向善行','恩典引向善行'),('Forgiveness is freely given by grace. The sermon also reads Ephesians 2:10: those created in Christ are called to live in the good works God prepares.','赦免是白白赐下的恩典；讲道也读以弗所书2:10，指出在基督里被造的人要行神所预备的善行。','赦免是白白賜下的恩典；講道也讀以弗所書2:10，指出在基督裡被造的人要行神所預備的善行。')),
('first-last','126','The Principle of First and Last',('The first and the last','首先与末后','首先與末後'),('The vineyard-workers parable challenges calculations of deserving and status. The sermon applies the first-and-last principle as a new way of thinking under God’s grace.','葡萄园工人的比喻挑战人对功劳与地位的计算；讲道把首先与末后的原则应用为恩典下新的思想方式。','葡萄園工人的比喻挑戰人對功勞與地位的計算；講道把首先與末後的原則應用為恩典下新的思想方式。')),
('greatness-service','127','whenever someone puts themselves first, there is immediate tension',('Greatness through service','以服事为大','以服事為大'),('Seeking the first place creates rivalry. Jesus redirects ambition toward becoming a servant, following his own example of giving his life.','争居首位带来竞争；耶稣引导门徒作仆人，效法他舍命服事的榜样。','爭居首位帶來競爭；耶穌引導門徒作僕人，效法他捨命服事的榜樣。')),
('grace-transformation','128','that forgiveness is not an end in itself',('Forgiveness and a transformed life','赦免与生命转变','赦免與生命轉變'),('The sermon distinguishes justification, sanctification and judgment. Received grace is expected to change conduct; forgiveness is not treated as an excuse to stay unchanged.','讲道区分称义、成圣与审判；领受的恩典应改变行为，赦免不是维持旧生活的借口。','講道區分稱義、成聖與審判；領受的恩典應改變行為，赦免不是維持舊生活的藉口。')),
('fruit-responsibility','133','the standard gets higher and higher',('Fruit and responsibility','结果子与责任','結果子與責任'),('The vineyard belongs to God, who looks for fruit. The sermon connects greater maturity and responsibility with a greater expectation of faithfulness.','葡萄园属于神，他寻找果子；讲道联系生命的成熟、责任的增加与更高的忠心要求。','葡萄園屬於神，他尋找果子；講道聯繫生命的成熟、責任的增加與更高的忠心要求。')),
('deny-self','318','The whole thinking of this society is self',('Denying ourselves and taking up the cross','舍己、背十字架','捨己、背十字架'),('Following Jesus challenges a life organised around self-interest. The sermon applies the call to deny ourselves and take up the cross to daily decisions.','跟随耶稣挑战以自我利益为中心的生活；讲道把舍己、背十字架应用在日常选择中。','跟隨耶穌挑戰以自我利益為中心的生活；講道把捨己、背十字架應用在日常選擇中。')),
]
for repo in [w]:
 entries=[]
 for id,sid,anchor,title,summary in P:
  f=repo/f'assets/sermons/en/{sid}.txt';text=f.read_text();assert anchor.lower() in text.lower(),(repo,sid,anchor)
  n=text.lower().index(anchor.lower());anchor=text[n:n+len(anchor)]
  entries.append(dict(id=id,title=loc(*title),summary=loc(*summary),sermonIds=[sid],sourceAnchors=[{'sermonId':sid,'locale':'en','text':anchor,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}]))
 (repo/'assets/bible_principles.json').write_text(json.dumps({'_meta':{'schema':1,'editorial':True,'author':'Pastor Eric H. H. Chang','method':'Selected study-guide summaries anchored in bundled sermons. Open the source for the original argument. Scripture links are the complete existing indexed references of each cited sermon; this is not a claim to exhaust every principle or every possible related Bible passage.','checkedAt':'2026-10-01'},'principles':entries},ensure_ascii=False,indent=2)+'\n')
print('wrote',len(E),'Passion events and',len(P),'source-anchored principles per app')
